name: CI for Jupyter Notebooks

on:
  push:
    branches:
      - pm-41
  pull_request:
    branches:
      - pm-41

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install nbconvert nbclient  

      - name: Run Jupyter Notebooks
        run: |
          for notebook in $(find . -name '*.ipynb'); do  
            echo "Executing $notebook"  
            jupyter nbconvert --to notebook --execute --inplace $notebook  
          done
