name: CI for Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install nbconvert nbclient ipykernel

      - name: Define Notebooks
        id: notebooks
        run: echo "notebooks=recipes/Getting_Started_with_Granite_Code.ipynb \
          recipes/CodeLLM_DevKit/generate_unit_tests.ipynb \
          recipes/CodeLLM_DevKit/validating_code_translation.ipynb" >> $GITHUB_ENV

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Run Jupyter Notebooks
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          for notebook in ${{ env.notebooks }}; do  
            echo "Executing $notebook"  
            jupyter nbconvert --to notebook --execute --inplace $notebook  
          done
